language: php

php:
    - 7.4
    - 8.0

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - cp .env.example .env

script:
    - vendor/bin/phpunit